# Generated by Django 5.1 on 2025-03-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_user_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
