# Generated by Django 5.1 on 2025-03-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stock_pe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_stocks',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.stock'),
        ),
        migrations.CreateModel(
            name='StockLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.league')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_stocks',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.stockleague'),
        ),
    ]
