# Generated by Django 5.1 on 2025-03-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_active_stocks_stockleague_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockleague',
            name='week',
        ),
    ]
