# Generated by Django 5.1 on 2025-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_stockleague_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_stocks',
        ),
        migrations.AddField(
            model_name='matchup',
            name='first_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='matchup',
            name='second_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
