# Generated by Django 5.1 on 2025-03-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userprofile_active_stocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='winner',
        ),
    ]
