# Generated by Django 5.1 on 2025-03-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_matchup_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
