# Generated by Django 5.1 on 2025-03-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_stock_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockleague',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockleagues', to='main.stock'),
        ),
    ]
